name: green
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0<3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

  animated_text_kit: ^4.2.1
  firebase_core: ^1.7.0
  firebase_auth: ^3.1.3
  cloud_firestore: ^2.5.3
  modal_progress_hud: ^0.1.3
  rflutter_alert: ^2.0.4
  encrypt: ^5.0.1
  get_storage: ^2.0.3
  pull_to_refresh: 1.6.3
  simple_animations: ^1.3.3
  flutter_gradient_colors: ^2.1.1
  http: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - images/
  uses-material-design: true